### ISSUE TITLE
howto use already available chroot instead of creating new one

### ISSUE THREAD

**Issue by picca** [debomatic/debomatic#35] opened 2017-08-23 13:41 UTC
Hello,

I have a bunch of schroot already available

```
root@sixs7:/var/tmp/build-propellor# schroot -l
chroot:UNRELEASED
chroot:UNRELEASED-amd64-sbuild
chroot:experimental
chroot:jessie-amd64-sbuild
chroot:rc-buggy
chroot:sid
chroot:stretch-amd64-sbuild
chroot:unstable-amd64-sbuild
source:stretch-amd64-sbuild
```

my debomatic config file contain this

```
[chroots]
profile=sbuild
commands=/usr/share/debomatic/sbuildcommands
```

but When I upload a package, I see this in the log

```
DEBUG: Module AutoPkgTest is blacklisted
DEBUG: Modules will be executed in this order: BuildCleaner, Contents, DateStamp, SourceUpload
DEBUG: pre_chroot hooks launched
DEBUG: pre_chroot hooks finished
DEBUG: Creating chroot unstable-amd64-debomatic
```
so my question is why debomatic doesn not use my 
<series>-<arch>-sbuild chroot and try to build one.

PS, it can not create it because I need an Apt proxy in order to download and update the chroot.

**Comment by picca** [comment] 2017-08-25 13:06
Ok; in thaht case what is the best way to teach debomatic what is the proxy to use for apt ?

**Comment by dktrkranz** [comment] 2017-08-25 13:14
I would drop a script in the chroot-setup-commands to create a file under /etc/apt/apt.conf.d which contains the right Acquire::http::proxy property.

I do something similar with [this simple script](https://github.com/debomatic/debomatic/blob/master/sbuildcommands/chroot-setup-commands/dpkg-speedup).

**Comment by picca** [comment] 2017-08-25 13:25
thanks I will think about this,
until now I used the schroot copyfiles in order to add the 20proxy files into /etc/apt/apt.conf.d

this way it works event  if the chroot is used outside debomatic.

**Comment by dktrkranz** [comment] 2018-01-15 15:54
Closing the issue because it works by design.

**Closed by dktrkranz** 2018-01-15 15:54 UTC
